version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'stream'
      MYSQL_USER: 'your_mysql_user'
      MYSQL_PASSWORD: 'your_mysql_password'
      MYSQL_ROOT_PASSWORD: 'your_mysql_root_password'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
  app:
    build: .
    ports:
      - '8501:8501'
    depends_on:
      - db
    volumes:
      - ./app:/app
      - ./mysql_data:/var/lib/mysql
